import testImage from '../assets/images/Пальто_1.png'

export const PRODUCTS = [
  {
    id: 1,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 2,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 3,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 4,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 5,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 6,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 7,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 8,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 9,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
  {
    id: 10,
    title: 'Мужское пальто',
    price: 5,
    description: 'Lorem',
    category: 'Пальто',
    image: testImage,
  },
]
